- hosts: localhost
  become: yes
  gather_facts: false
  tasks:

  - name: Remove existing lasback container
    community.docker.docker_container:
      name: lasback
      keep_volumes: true
      state: absent

  - name: Create lasback build directory
    ansible.builtin.file:
      path: /data/lasback/docker
      state: directory
      mode: '0755'

  - name: Write Dockerfile
    ansible.builtin.copy:
      dest: /data/lasback/docker/Dockerfile
      mode: '0644'
      content: |
        FROM node:22.14-alpine3.21
        RUN apk add --no-cache wget unzip
        WORKDIR /opt/lasback/
        RUN wget https://github.com/Zombitch/lasback/archive/refs/heads/main.zip \
            && unzip main.zip \
            && rm -f main.zip
        WORKDIR /opt/lasback/lasback-main
        RUN npm ci --omit=dev
        RUN addgroup -S appgroup && adduser -S appuser -G appgroup
        USER appuser
        EXPOSE 4000
        CMD ["npm","start"]

  - name: Delete previous lasback image
    community.docker.docker_image:
      name: lasback
      state: absent
      force_absent: true

  - name: Build lasback image
    community.docker.docker_image:
      name: lasback
      source: build
      build:
        path: /data/lasback/docker

  - name: Run lasback container
    community.docker.docker_container:
      container_default_behavior: no_defaults
      name: lasback
      image: lasback
      hostname: "{{ host }}"
      state: started
      restart_policy: always
      exposed_ports :
        - 4000
      volumes:
        - lasback_data:/opt/lasback/lasback-main
      env:
        NODE_ENV: "production"
        PORT: "4000"
        CORS_ALLOWED_ORIGINS: "{{ cors }}"
        API_KEYS: "{{ apikeys }}"
        MONGO_URI: "{{ mongoURI }}"
        SESSION_SECRET: "{{ sessionSecret }}"
        JWT_SECRET: "{{ jwtSecret }}"
      networks:
        - name: "{{ network }}"
